services:
  db:
    image: postgres:16
    container_name: gonotes_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gonotes_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["./run.sh"]

volumes:
  postgres_data:
