CREATE TABLE IF NOT EXISTS Notes (
    id SERIAL PRIMARY KEY,
    note_text TEXT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);